#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pkm_level2_converter'

if ARGV.first
  PkmLevel2Converter::PKMXml.new(ARGV.first).save_as_level2

else
  arr_of_local_xml = Dir['*.xml']
  if arr_of_local_xml.empty?
    puts 'Error: No .xml file found.'
    puts 'Usage "pkmlevel2 filename.xml"'
  else
    arr_of_local_xml.each do |xml_file|
      PkmLevel2Converter::PKMXml.new(xml_file).save_as_level2
    end
  end
  puts 'Press ENTER to close.'
  gets
end
