#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pkm_level2_converter'

if ARGV.first
  orig_file_name = ARGV.first
  converter = PkmLevel2Converter::PKMXml.new(orig_file_name)
  converter.convert_org_id_to_level2

else
  arr_of_local_xml = Dir['*.xml']
  if arr_of_local_xml.empty?
    puts 'Error: No .xml file found.'
    puts 'Usage "pkmlevel2 filename.xml"'
  else
    arr_of_local_xml.each do |xml_file|
      converter = PkmLevel2Converter::PKM.new(xml_file)
      converter.convert_pkm
    end
  end
  puts 'Press ENTER to close.'
  gets
end
